## basic config
languageCode = "en-us"
title = "hgmiguel.MX"
baseURL = "http://hgmiguel.mx/"
theme = "hugo-goa"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Miguel Angel Huerta González"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[params]
author = "Miguel Angel Huerta González"
intro = "DevOps practitioner"
description = "AWS solutions architecht" 
authorimage = "perfil.jpg"
dateformat = "Jan 2, 2006"

[params.social]
github = "hgmiguel"
linkedin = "hgmiguel"
twitter = "hgmiguel"
facebook = "hgmiguel"
#google = "100718508856228319369"
#stackoverflow = "430204/hgmiguel"
email = "hgmiguel@gmail.com"

## Extras
[params.extra]
copyright = "© 2020. Miguel Angel Huerta. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = false
hightlightjs = true


## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "want to donate?"
    identifier = "donate"
    weight = 300
    url = "/donate/"
