## basic config
languageCode = "en-us"
title = "hgmiguel.MX Miguel Huerta"
baseURL = "http://hgmiguel.mx/"
theme = "soho"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Miguel Angel Huerta González"

enableInlineShortcodes = true

summarylength = 10
enableEmoji = true

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4

[params]
author = "Miguel Angel Huerta González"
intro = "AWS solutions architecht" 
description = "DevOps practitioner"
authorimage = "perfil.jpg"
profilePicture = "img/perfil.jpg"
dateformat = "Jan 2, 2006"
copyright = "Miguel Angel Huerta González"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "hgmiguel"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "hgmiguel"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "hgmiguel"



[menu]
## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "post"
    url = "/post/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "Want to donate?"
    identifier = "donate"
    weight = 300
    url = "/donate/"


[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "hgmiguel.mx"

URL = "s3://hgmiguel.mx?region=us-east-1"

# [[deployment.matchers]] configure behavior for files that match the Pattern.
# Samples:

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
