AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Environment:
    Type: String
    Default: testing
    Description: environment
  CostCenter:
    Type: String
    Default: hgmigue-labs

Resources:
  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh to client host
      VpcId:
        Fn::ImportValue:
          !Sub "${Environment}:VPC"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
Outputs:
  Bastion:
    Description: Bastion host SG
    Value: !Ref BastionSecurityGroup
    Export: 
      Name: !Sub "${Environment}:BastionSecurityGroup"

  

