AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Type: String
    Default: testing
    Description: environment
  CidrBlock:
    Type: String
    Default: 10.0.0.0/16 
  CostCenter:
    Type: String
    Default: hgmigue-labs

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: !Sub '${AWS::Region}:${AWS::AccountId}:${Environment}:Vpc'
      - Key: CostCenter
        Value: !Ref CostCenter
  InternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
      - Key: Name
        Value: !Sub '${AWS::Region}:${AWS::AccountId}:${Environment}:InternetGateway'
      - Key: CostCenter
        Value: !Ref CostCenter
  AttachGateway:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties: 
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

Outputs:
  VPC:
    Description: 'VPC'
    Value: !Ref VPC
    Export:
      Name: !Sub '${Environment}:VPC'
  InternetGateway:
    Description: 'Internet Gateway'
    Value: !Ref InternetGateway
    Export:
      Name: !Sub '${Environment}:InternetGateway'


